### ISSUE TITLE
Insert snippet at cursor location rather than at end of line

### ISSUE THREAD

**Issue by jeffrey-xiao** [joereynolds/vim-minisnip#10]
Is it possible to insert the snippet at the cursor location? I'm mostly using minisnip for LaTex and it's frustrating when I attempt to evaluate a snippet in the middle of a line only to have it insert at the end of the line.

I was thinking instead of appending after the line and joining them, we could put it in an expression register and then paste it. It could look something like this:
`silent! execute "normal \"=\"".join(lns, '\n')."\"\<C-M>P"`

There might be cleaner solutions though.

**Comment by joereynolds** [comment]
I'm not really sure I understand what you mean, the snippet gets inserted where the snippet placeholder {{++}} is, not at any other location

**Comment by jeffrey-xiao** [comment]
Sorry, I realized that I wasn't very clear.

Let's say I had a snippet called `frac` which is `\frac{{{++}}}{{{++}}}{{++}}`

If I had a line like `$ frac| $` where `|` is where my cursor is, and I pressed Tab, I expect minisnip to put the template at my cursor. 

So I would expect something like this:
`$ \frac{{{++}}}{{{++}}}{{++}} $`

However, instead I get something like this:
`$   $\frac{{{++}}}{{{++}}}{{++}}`

This is obviously a really minor issue I have with minisnip and something I could definitely work around, but it would be really nice if it could insert the snippet at my cursor.

**Comment by Carpetsmoker** [comment]
Here's a clearer example; snippet contents in `~/.vim/minisnip/test`:

    hello

Buffer contents:

    abc test xyz

Expanding the `test` snippet with `<Tab>` gives:

    abc  xyz hello

Whereas the expected would be:

   abc hello xyz

**Comment by sigzero** [comment]
I would expect a separate mechanism might be needed. Since {++}  expands in
place, maybe {--} expands at the cursor position or something like that.

**Comment by Carpetsmoker** [comment]
> I would expect a separate mechanism might be needed. Since {++} expands in place, maybe {--} expands at the cursor position or something like that.

I don't think this is related to placeholder expansion at all? My example doesn't use placeholders.
