### ISSUE TITLE
Unexpected clearing of line contents upon snippet expansion

### ISSUE THREAD

**Issue by kennethlee** [joereynolds/vim-minisnip#16]
Let's say I have snippet `_html_.` that expands into `class="{{++}}"`. I want to add a class to a `<th>` element like so:

```
<table>
  <tr>
    <th .|>Title</th>
  </tr>
</table>
```

When I hit Tab for expansion, I expect this:

```
<table>
  <tr>
    <th class="|">Title</th>
  </tr>
</table>
```

but instead get this:

```
<table>
  <tr>
    class="|"
  </tr>
</table>
```

**Comment by joereynolds** [comment]
Hey @kennethlee 

I've noticed this too, I think it might be a regression (hence why I've started adding tests in).
I'll try and find the offending commit when I get the time.

Cheers!

**Comment by joereynolds** [comment]
As an update, I've checked Keyboardfire's version and the issue is there too (though in a slightly different way).

Thanks for the report!

**Comment by kennethlee** [comment]
Thanks for quick response, @joereynolds, and keep up the good work!

**Comment by joereynolds** [comment]
Hey @kennethlee 

@thepith kindly made a pr that fixes this issue.
Thanks for the report!

**Comment by kennethlee** [comment]
Hey @joereynolds, thanks for the heads up. @thepith, thank you for your efforts!

I'm unfortunately experiencing some wonkiness with the latest pr.

Say I have a snippet, `_html_id`, that expands to `id="{{++}}"{{++}}`. If I try to expand the snippet in a situation like this (note the lack of any space between "id" trigger word and the existing `class` attribute):

```
<ul id|class="listy-list">
  <li>text</li>
</ul>
```

... I get this (the class attribute vanishes):

```
<ul id="|"{{++}} "listy-list">
  <li>text</li>
</ul>
```

Another example: here, I'm adding an `id` to an unordered list.

```
<ul class="listy-list" id|>
  <li>text</li>
</ul>
```

... the result:

```
<ul class="listy-list" > id="|"{{++}}
  <li>text</li>
</ul>
```

**Comment by thepith** [comment]
@kennethlee I submitted a new pull request. Can you check if it resolves your problem?
