### ISSUE TITLE
Remove `<C-x><C-t>` mapping and encourage people to use 'completefunc' instead

### ISSUE THREAD

**Issue by hauleth** [joereynolds/vim-minisnip#19]
This would simplify setup and `minisnip#complete` function

**Comment by Carpetsmoker** [comment]
The problem with this is that people may already use `completefunc` for the filetype-specific completion. I don't think we want to override that.

**Comment by hauleth** [comment]
@Carpetsmoker even then it would be much better IMHO to provide support for using minisnip as `'completefunc'` for those who use `'omnifunc'` for filetype completion. It could be done quite simply, so I will try to write some PR soon.
