### ISSUE TITLE
Placeholders without additional input?

### ISSUE THREAD

**Issue by teranex** [joereynolds/vim-minisnip#25]
Would it be possible to add support for placeholders which are skipped when Tab-ing, so they can just receive their values from vimscript?
I'm giving minisnip a try (currently using Ultisnips).
When in Ultisnips I have the following snippet, I only have to tab once and I can immediately start typing the title

```
# `!v strftime("%Y-%m-%d %H:%M")` ${1:title}
```

However in minisnip I would have to tab twice with the following similar snippet:
```
# {{+~strftime("%Y-%m-%d %H:%M")+}} {{+title+}}
```

Maybe it could be a syntax such as:

     {{`strftime(...)`}}

**Comment by joereynolds** [comment]
Good idea!
