### ISSUE TITLE
Snippets for multiple filetypes

### ISSUE THREAD

**Issue by chaucerbao** [joereynolds/vim-minisnip#31]
It would be helpful if there was a way to associate a snippet with multiple filetypes.  For example:
- CSS snippets could be made available for SCSS, Stylus, and Less filetypes.
- Similarly, Javascript snippets could be made available for TypeScript filetypes.

Currently, if I want a snippet to be available to for >1 filetype, I have to make it global.

**Comment by Carpetsmoker** [comment]
You can use multiple filetypes, and this should work for many of these cases. e.g. `set filetype=css.less`.

The `less` filetype already loads the `css` one:

    runtime! syntax/css.vim
    runtime! after/syntax/css.vim

so this shouldn't have too many side-effects.

The same applies for the `scss` filetype, although I'm not sure about TypeScript, as that doesn't seem to be in the standard Vim distribution.

**Comment by chaucerbao** [comment]
Seems obvious now that you mention it.
