### ISSUE TITLE
Praise + Feature request: placeholders to paste content

### ISSUE THREAD

**Issue by manasthakur** [joereynolds/vim-minisnip#39]
Hi @joereynolds,

I loved this plugin and switched to it since its inception. After @KeyboardFire stopped its development, I tried [maintaining a fork](https://github.com/manasthakur/vim-minisnip/) for some time, before switching to your fork completely. I must say you have taken it to new heights. For example, the facility to have 'final delimiters' (not highlighted in the README yet) is really cool, and solved my problems with LaTex snippets (now I can come back to the body of an environment after completing its end tag, for example.).

I have one feature request. Say I have some text:
```
sum = a + b;
```

Now say I want to enclose it in an `if` snippet:
```
if ({{++}}) {
    sum = a + b;
    {{++}}
}
```

Ultisnips has this feature where we can have some $VISUAL placeholders that can be filled automatically with the selected text, if the snippet is triggered from visual mode. Currently, I have two options:
(a) Either use surround.vim to surround the selection with braces, and write the if manually -- no snippet support.
(b) Delete the text, trigger the `if` snippet, and then paste the text indented (I have a map for it).

Can we have a special placeholder (for the body of `if` in this case) that works from the visual mode, such that the selected text replaces the placeholder? Probably not a trivial problem, but I guess implementing it will not impact the minimalism and speed of the plugin much.

**Comment by joereynolds** [comment]
Hey @manasthakur,

Thanks for the praise, though I think that should all be directed to the contributors, I've actually done very little to vim-minisnips core (I've added a Travis CI build and tests in Vader).

As for the feature request, it does look non-trivial and to be honest, the code looks to me in need of a refactor in terms of readability before anything else happens to it.

Feel free to submit a PR though :)

**Comment by manasthakur** [comment]
Hi @joereynolds,

I am working on the feature and it's almost ready to be submitted as a PR, except for a sanity cleanup. I need to unlet a variable after all the placeholders for the current snippet have been expanded. Can you please point me to the correct place in the code where I can do the same?

**Comment by manasthakur** [comment]
Never mind, got the correct `finally` block. Will submit the PR soon :)
