### ISSUE TITLE
Line complete adds whitespace

### ISSUE THREAD

**Issue by denarced** [joereynolds/vim-minisnip#42]
There's a rather annoying bug that affects files of all types when using this plugin. To reproduce:
1. Enter insert mode
2. Optionally type something
3. Complete line (vim help tag: i_CTRL-X_CTRL-L), select a line, and press enter

What's suppose to happen is that the newly added line is exactly like the line that was selected and the cursor is moved to the next line. What happens is that whitespace (so far I've seen a single space added) is added to the end of the edited line.

I verified this by first using vim with "vim -u NONE"; the issue disappeared. Then by disabling my plugins one at a time. The behavior stopped when vim-minisnip was commented out.

Specs:
* Vim 8.0 (patches 1-1453)
* Ubuntu 18.04.2 LTS 64 bit (all packages up to date)
* Installed vim packages: vim, vim-common, vim-runtime, vim-tiny
* Plugin manager: vim-plug
* vim-minisnip changeset: b5bcaff0ddea13d3ce2cf25f4dc88b0569da60b1

**Comment by arp242** [comment]
Essentially same as #43
